# Generated by Django 2.1.1 on 2018-10-18 19:41

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180830_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=256, validators=[tweets.validators.validate_content]),
        ),
    ]
